[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build]
  command = "npm run build"
  publish = "build"

[build.environment]
  REACT_APP_NEWS_API_KEY = "8488cb778da840eab79d8d2e64caaf03"